//! This code was AUTOGENERATED using the Codama library.
use crate::types::payment_frequency::PaymentFrequency;
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, serde::Serialize)]
pub struct ContractState {
    pub version: u8,
    pub to_close: bool,
    pub rate: u64,
    pub duration_min: u64,
    pub duration_max: u64,
    pub payments_feq: PaymentFrequency,
    pub fleet: Pubkey,
    pub game_id: Pubkey,
    pub current_rental_state: Pubkey,
    pub owner: Pubkey,
    pub owner_token_account: Pubkey,
    pub owner_profile: Pubkey,
    pub bump: u8,
}

impl ContractState {
    pub fn decode(data: &[u8]) -> Option<Self> {
        use shared::decode_with_discriminator;
        const DISCRIMINATOR: &[u8] = &[190, 138, 10, 223, 189, 116, 222, 115];
        decode_with_discriminator::<Self>(data, DISCRIMINATOR)
    }
}
