//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, serde::Serialize)]
pub struct Fleet {
    pub version: u8,
    pub game_id: Pubkey,
    pub owner_profile: Pubkey,
    pub fleet_ships: Pubkey,
    pub sub_profile: Pubkey,
    pub sub_profile_invalidator: Pubkey,
}

impl Fleet {
    pub fn decode(data: &[u8]) -> Option<Self> {
        use shared::decode_with_discriminator;
        const DISCRIMINATOR: &[u8] = &[109, 207, 251, 48, 106, 2, 136, 163];
        decode_with_discriminator::<Self>(data, DISCRIMINATOR)
    }
}
