//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, serde::Serialize)]
pub struct RentalState {
    pub version: u8,
    pub borrower: Pubkey,
    pub thread: Pubkey,
    pub contract: Pubkey,
    pub owner_token_account: Pubkey,
    pub rate: f64,
    pub start_time: i64,
    pub end_time: i64,
    pub cancelled: bool,
    pub bump: u8,
}

impl RentalState {
    pub fn decode(data: &[u8]) -> Option<Self> {
        use shared::decode_with_discriminator;
        const DISCRIMINATOR: &[u8] = &[97, 162, 29, 222, 251, 251, 180, 244];
        decode_with_discriminator::<Self>(data, DISCRIMINATOR)
    }
}
