//! This code was AUTOGENERATED using the Codama library.
use shared::ClockData;
use crate::types::exec_context::ExecContext;
use crate::types::serializable_instruction::SerializableInstruction;
use crate::types::trigger::Trigger;
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, serde::Serialize)]
pub struct Thread {
    /// The owner of this thread.
    pub authority: Pubkey,
    /// The bump, used for PDA validation.
    pub bump: u8,
    /// The cluster clock at the moment the thread was created.
    pub created_at: ClockData,
    /// The context of the thread's current execution state.
    pub exec_context: Option<ExecContext>,
    /// The number of lamports to payout to workers per execution.
    pub fee: u64,
    /// The id of the thread, given by the authority.
    pub id: Vec<u8>,
    /// The instructions to be executed.
    pub instructions: Vec<SerializableInstruction>,
    /// The name of the thread.
    pub name: String,
    /// The next instruction to be executed.
    pub next_instruction: Option<SerializableInstruction>,
    /// Whether or not the thread is currently paused.
    pub paused: bool,
    /// The maximum number of execs allowed per slot.
    pub rate_limit: u64,
    /// The triggering event to kickoff a thread.
    pub trigger: Trigger,
}

impl Thread {
    pub fn decode(data: &[u8]) -> Option<Self> {
        use shared::decode_with_discriminator;
        const DISCRIMINATOR: &[u8] = &[186, 27, 154, 111, 51, 36, 159, 90];
        decode_with_discriminator::<Self>(data, DISCRIMINATOR)
    }
}
