//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;

#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash, serde::Serialize)]
pub struct ClockData {
    pub slot: u64,
    pub epoch: u64,
    pub unix_timestamp: i64,
}
