//! This code was AUTOGENERATED using the Codama library.
use crate::types::trigger_context::TriggerContext;
use carbon_core::borsh;
/// The execution context of a particular transaction thread.

#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash, serde::Serialize)]
pub struct ExecContext {
    /// Index of the next instruction to be executed.
    pub exec_index: u64,
    /// Number of execs since the last tx reimbursement.
    /// To be deprecated in v3 since we now reimburse for every transaction.
    pub execs_since_reimbursement: u64,
    /// Number of execs in this slot.
    pub execs_since_slot: u64,
    /// Slot of the last exec
    pub last_exec_at: u64,
    /// Unix timestamp of last exec
    pub last_exec_timestamp: i64,
    /// Context for the triggering condition
    pub trigger_context: TriggerContext,
}
