//! This code was AUTOGENERATED using the Codama library.

// ora in shared
// pub mod clock_data;
// pub mod equality;
pub mod exec_context;
pub mod payment_frequency;
// pub mod serializable_account;
pub mod serializable_instruction;
pub mod thread_response;
pub mod trigger;
pub mod trigger_context;

// moduli ora condivisi in shared
