//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;

#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash, serde::Serialize)]
pub enum PaymentFrequency {
    Decasecond,
    Minute,
    Hourly,
    Daily,
    Weekly,
    Monthly,
}
