//! This code was AUTOGENERATED using the Codama library.
use shared::SerializableAccount;
use carbon_core::borsh;
use solana_pubkey::Pubkey;
/// The data needed execute an instruction on Solana.

#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash, serde::Serialize)]
pub struct SerializableInstruction {
    /// Pubkey of the instruction processor that executes this instruction
    pub program_id: Pubkey,
    /// Metadata for what accounts should be passed to the instruction processor
    pub accounts: Vec<SerializableAccount>,
    /// Opaque data passed to the instruction processor
    pub data: Vec<u8>,
}
