import * as utils from "@utils/utils.js";
import "./app/debug.js";
import "./app.js";
import { setSidebarVisible } from "@ui/sidebar.js";
import { formatCraftingType } from "@ui/craftingType.js";
import { renderCraftingDetailsRows } from "@ui/renderDetails.js";
import { updateProgress, displayPartialResults, displayResults, toggleFleet } from "./app.js";
window.toggleFleet = toggleFleet;
window.copyToClipboard = utils.copyToClipboard;
window.inferRecipeName = utils.inferRecipeName;
window.inferMaterialLabel = utils.inferMaterialLabel;
window.formatCraftingType = formatCraftingType;
window.setSidebarVisible = setSidebarVisible;
window.renderCraftingDetailsRows = renderCraftingDetailsRows;
window.updateProgress = updateProgress;
window.displayPartialResults = displayPartialResults;
window.displayResults = displayResults;
window.currentProfileId = null;
window.analysisStartTime = null;
window.progressInterval = null;
window.lastAnalysisParams = null;
import { analyzeFees } from "@services/api.js";
window.analyzeFees = analyzeFees;
