// Operation mapping for SAGE transactions
// Exported as default for use in 06-transactions.ts

const OP_MAP: { [key: string]: string } = {
    // Fleet Movement & State
    'createFleet': 'CreateFleet',
    'disbandFleet': 'DisbandFleet',
    'forceDisbandFleet': 'ForceDisbandFleet',
    'disbandedFleetToEscrow': 'DisbandedFleetToEscrow',
    'closeDisbandedFleet': 'CloseDisbandedFleet',
    'idleToLoadingBay': 'IdleToLoadingBay',
    'IdleToLoadingBay': 'IdleToLoadingBay',
    'loadingBayToIdle': 'LoadingBayToIdle',
    'LoadingBayToIdle': 'LoadingBayToIdle',
    'idleToRespawn': 'IdleToRespawn',
    'IdleToRespawn': 'IdleToRespawn',
    'loadingBayToRespawn': 'LoadingBayToRespawn',
    'LoadingBayToRespawn': 'LoadingBayToRespawn',
    'respawnToLoadingBay': 'Respawn',
    'RespawnToLoadingBay': 'Respawn',
    'mineAsteroidToRespawn': 'MineToRespawn',
    'MineAsteroidToRespawn': 'MineToRespawn',
    'fleetStateHandler': 'FleetStateHandler',
    'FleetStateHandler': 'FleetStateHandler',
    // Warp & Movement (raw names)
    'startSubwarp': 'StartSubwarp',
    'StartSubwarp': 'StartSubwarp',
    'stopSubwarp': 'StopSubwarp',
    'StopSubwarp': 'StopSubwarp',
    'warpToCoordinate': 'WarpToCoordinate',
    'WarpToCoordinate': 'WarpToCoordinate',
    'warpLane': 'WarpLane',
    'WarpLane': 'WarpLane',
    'planetExitWarp': 'PlanetExitWarp',
    'PlanetExitWarp': 'PlanetExitWarp',
    // Mining (raw names)
    'startMiningAsteroid': 'StartMiningAsteroid',
    'StartMiningAsteroid': 'StartMiningAsteroid',
    'start_mining_asteroid': 'StartMiningAsteroid',
    'StopMiningAsteroid': 'StopMiningAsteroid',
    'stopMiningAsteroid': 'StopMiningAsteroid',
    'stop_mining_asteroid': 'StopMiningAsteroid',
    'mineAsteroid': 'MineAsteroid',
    'MineAsteroid': 'MineAsteroid',
    'mine_asteroid': 'MineAsteroid',
    'miningAsteroid': 'MiningAsteroid',
    'MiningAsteroid': 'MiningAsteroid',
    'mining_asteroid': 'MiningAsteroid',
    // Scanning / SDU (raw names)
    'scanForSurveyDataUnits': 'ScanForSurveyDataUnits',
    'ScanForSurveyDataUnits': 'ScanForSurveyDataUnits',
    'scan_for_survey_data_units': 'ScanForSurveyDataUnits',
    'scanSurveyDataUnits': 'ScanSurveyDataUnits',
    'ScanSurveyDataUnits': 'ScanSurveyDataUnits',
    'scan_survey_data_units': 'ScanSurveyDataUnits',
    'dropExpiredSurveyDataUnits': 'DropExpiredSurveyDataUnits',
    'DropExpiredSurveyDataUnits': 'DropExpiredSurveyDataUnits',
    'drop_expired_survey_data_units': 'DropExpiredSurveyDataUnits',
    'claimSurveyDataUnits': 'ClaimSurveyDataUnits',
    'ClaimSurveyDataUnits': 'ClaimSurveyDataUnits',
    'claim_survey_data_units': 'ClaimSurveyDataUnits',
    // Fleet Cargo Operations (raw names)
    'depositCargoToFleet': 'DepositCargoToFleet',
    'DepositCargoToFleet': 'DepositCargoToFleet',
    'withdrawCargoFromFleet': 'WithdrawCargoFromFleet',
    'WithdrawCargoFromFleet': 'WithdrawCargoFromFleet',
    'transferCargoWithinFleet': 'TransferCargoWithinFleet',
    'TransferCargoWithinFleet': 'TransferCargoWithinFleet',
    'transferCargo': 'TransferCargo',
    'TransferCargo': 'TransferCargo',
    'legitimizeCargo': 'LegitimizeCargo',
    'LegitimizeCargo': 'LegitimizeCargo',
    'consumeCargo': 'ConsumeCargo',
    'ConsumeCargo': 'ConsumeCargo',
    // Game Cargo Operations  
    'depositCargoToGame': 'DepositCargoGame',
    'withdrawCargoFromGame': 'WithdrawCargoGame',
    // Starbase Cargo Operations
    'transferCargoAtStarbase': 'TransferCargoStarbase',
    'createCargoPod': 'CreateCargoPod',
    'removeCargoPod': 'RemoveCargoPod',
    // Fleet Management
    'addShipToFleet': 'AddShip',
    'addShipEscrowToFleet': 'AddShipEscrow',
    'removeShipEscrow': 'RemoveShipEscrow',
    'updateShipEscrow': 'UpdateShipEscrow',
    'updateShipInFleet': 'UpdateShipInFleet',
    'loadFleetCrew': 'LoadCrew',
    'unloadFleetCrew': 'UnloadCrew',
    'rearmFleet': 'Rearm',
    'refuelFleet': 'Refuel',
    // Crafting (add snake_case variants too)
    'createCraftingProcess': 'CraftStart',
    'create_crafting_process': 'CraftStart',
    'startCraftingProcess': 'CraftStart',
    'start_crafting_process': 'CraftStart',
    'stopCraftingProcess': 'CraftStop',
    'stop_crafting_process': 'CraftStop',
    'cancelCraftingProcess': 'CraftCancel',
    'cancel_crafting_process': 'CraftCancel',
    'closeCraftingProcess': 'CraftClose',
    'close_crafting_process': 'CraftClose',
    'claimCraftingOutputs': 'CraftClaim',
    'claim_crafting_outputs': 'CraftClaim',
    'claimCraftingNonConsumables': 'CraftClaimNonCons',
    'claim_non_consumable_ingredient': 'CraftClaimNonCons',
    'depositCraftingIngredient': 'CraftDeposit',
    'deposit_crafting_ingredient': 'CraftDeposit',
    'withdrawCraftingIngredient': 'CraftWithdraw',
    'withdraw_crafting_ingredient': 'CraftWithdraw',
    'burnCraftingConsumables': 'CraftBurn',
    'burn_consumable_ingredient': 'CraftBurn',
    'claim_recipe_output': 'CraftClaim',
    'claimRecipeOutput': 'CraftClaim',
    // Recipe & facility management mapped to generic 'Crafting' category
    'add_consumable_input_to_recipe': 'Crafting',
    'add_non_consumable_input_to_recipe': 'Crafting',
    'add_output_to_recipe': 'Crafting',
    'add_recipe_ingredient': 'Crafting',
    'remove_consumable_input_from_recipe': 'Crafting',
    'remove_non_consumable_input_from_recipe': 'Crafting',
    'remove_output_from_recipe': 'Crafting',
    'remove_recipe_ingredient': 'Crafting',
    'register_recipe': 'Crafting',
    'register_craftable_item': 'Crafting',
    'register_crafting_facility': 'Crafting',
    'register_recipe_category': 'Crafting',
    'register_crafting_facility_recipe_category': 'Crafting',
    'deregister_crafting_facility': 'Crafting',
    'deregister_recipe_category': 'Crafting',
    'legitimize_recipe_ingredient': 'Crafting',
    'drain_craftable_item_bank': 'Crafting',
    'initialize_domain': 'Crafting',
    'update_recipe': 'Crafting',
    'update_recipe_category': 'Crafting',
    'update_crafting_facility': 'Crafting',
    'remove_crafting_facility_recipe_category': 'Crafting',
    // Starbase Crafting
    'createStarbaseCraftingProcess': 'StarbaseCraftStart',
    'closeStarbaseCraftingProcess': 'StarbaseCraftClose',
    'closeResourceCraftingProcess': 'ResourceCraftClose',
    // Starbase Operations
    'startStarbaseUpgrade': 'StarbaseUpgradeStart',
    'completeStarbaseUpgrade': 'StarbaseUpgradeComplete',
    'submitStarbaseUpgradeResource': 'StarbaseUpgradeSubmit',
    'depositStarbaseUpkeepResource': 'StarbaseUpkeepDeposit',
    'registerStarbase': 'RegisterStarbase',
    'registerStarbasePlayer': 'RegisterStarbasePlayer',
    'deregisterStarbase': 'DeregisterStarbase',
    'updateStarbase': 'UpdateStarbase',
    // Crew
    'addCrewToGame': 'AddCrew',
    'removeCrewFromGame': 'RemoveCrew',
    'closePlayerCrewRecord': 'CloseCrewRecord',
    'registerSageCrewConfig': 'RegisterCrewConfig',
    'devAddCrewToGame': 'DevAddCrew',
    // Sector & Discovery
    'discoverSector': 'DiscoverSector',
    'registerSector': 'RegisterSector',
    'updateSector': 'UpdateSector',
    'addConnection': 'AddConnection',
    'removeConnection': 'RemoveConnection',
    // Resources & Mining Items
    'registerMineItem': 'RegisterMineItem',
    'deregisterMineItem': 'DeregisterMineItem',
    'updateMineItem': 'UpdateMineItem',
    'registerResource': 'RegisterResource',
    'deregisterResource': 'DeregisterResource',
    'updateResource': 'UpdateResource',
    // Ships
    'registerShip': 'RegisterShip',
    'setNextShip': 'SetNextShip',
    'invalidateShip': 'InvalidateShip',
    // Planets & Stars
    'registerPlanet': 'RegisterPlanet',
    'updatePlanet': 'UpdatePlanet',
    'registerStar': 'RegisterStar',
    'updateStar': 'UpdateStar',
    // Game Management
    'initGame': 'InitGame',
    'initGameState': 'InitGameState',
    'manageGame': 'ManageGame',
    'updateGame': 'UpdateGame',
    'updateGameState': 'UpdateGameState',
    // Player Profile
    'registerSagePlayerProfile': 'RegisterProfile',
    // Progression
    'registerProgressionConfig': 'RegisterProgression',
    'deregisterProgressionConfig': 'DeregisterProgression',
    'updateProgressionConfig': 'UpdateProgression',
    'registerSagePointsModifier': 'RegisterPointsModifier',
    'incrementPoints': 'IncrementPoints',
    'IncrementPoints': 'IncrementPoints',
    // Survey Data Units
    'registerSurveyDataUnitTracker': 'RegisterSDUTracker',
    'deregisterSurveyDataUnitTracker': 'DeregisterSDUTracker',
    'updateSurveyDataUnitTracker': 'UpdateSDUTracker',
    // Rental
    'addRental': 'AddRental',
    'changeRental': 'ChangeRental',
    'invalidateRental': 'InvalidateRental',
    'enableSubProfileInvalidator': 'EnableSubProfileInvalidator',
    // Certificates
    'registerCertificate': 'RegisterCertificate',
    // Token Operations (SPL Token program instructions)
    'approve': 'Approve',
    'Approve': 'Approve',
    'burn': 'Burn',
    'Burn': 'Burn',
    'transfer': 'Transfer',
    'Transfer': 'Transfer',
    // Dev Tools
    'devDepositCargoToGame': 'DevDepositCargo',
    'Craft': 'Crafting',
    'craft': 'Crafting',
    // Fleet Abilities & Repairs
    'reloadFleetAbilityPower': 'ReloadAbility',
    'ReloadFleetAbilityPower': 'ReloadAbility',
    'repairDockedFleet': 'RepairDocked',
    'RepairDockedFleet': 'RepairDocked',
    'repairIdleFleet': 'RepairIdle',
    'RepairIdleFleet': 'RepairIdle',
    'repairStarbase': 'RepairStarbase',
    'RepairStarbase': 'RepairStarbase',
    // Combat Operations
    'attackFleet': 'AttackFleet',
    'AttackFleet': 'AttackFleet',
    'attackStarbase': 'AttackStarbase',
    'AttackStarbase': 'AttackStarbase',
    'retrieveLoot': 'RetrieveLoot',
    'RetrieveLoot': 'RetrieveLoot',
    // Combat Events
    'battleLogEvent': 'BattleLog',
    'BattleLogEvent': 'BattleLog',
    'combatInitiatedEvent': 'CombatInitiated',
    'CombatInitiatedEvent': 'CombatInitiated',
    'combatLootDropEvent': 'CombatLootDrop',
    'CombatLootDropEvent': 'CombatLootDrop',
    'combatParticipantEvent': 'CombatParticipant',
    'CombatParticipantEvent': 'CombatParticipant',
    'starbaseCombatEvent': 'StarbaseCombat',
    'StarbaseCombatEvent': 'StarbaseCombat',
    // Certificates
    'mintCertificate': 'MintCertificate',
    'MintCertificate': 'MintCertificate',
    'redeemCertificate': 'RedeemCertificate',
    'RedeemCertificate': 'RedeemCertificate',
    'createCertificateMint': 'CreateCertificateMint',
    'CreateCertificateMint': 'CreateCertificateMint',
    // Starbase Sync & Upgrade
    'syncStarbasePlayer': 'SyncStarbasePlayer',
    'SyncStarbasePlayer': 'SyncStarbasePlayer',
    'syncStarbaseUpgradeIngredients': 'SyncStarbaseUpgrade',
    'SyncStarbaseUpgradeIngredients': 'SyncStarbaseUpgrade',
    'createStarbaseUpgradeResourceProcess': 'StarbaseUpgradeResource',
    'CreateStarbaseUpgradeResourceProcess': 'StarbaseUpgradeResource',
    'closeUpgradeProcess': 'CloseUpgrade',
    'CloseUpgradeProcess': 'CloseUpgrade',
    // Cargo & Fleet Management
    'forceDropFleetCargo': 'ForceDropCargo',
    'ForceDropFleetCargo': 'ForceDropCargo',
    'removeInvalidShipEscrow': 'RemoveInvalidShip',
    'RemoveInvalidShipEscrow': 'RemoveInvalidShip',
    'closeFleetCargoPodTokenAccount': 'CloseFleetCargoPod',
    'CloseFleetCargoPodTokenAccount': 'CloseFleetCargoPod',
    'closeStarbaseCargoTokenAccount': 'CloseStarbaseCargo',
    'CloseStarbaseCargoTokenAccount': 'CloseStarbaseCargo',
    // Banks
    'drainMineItemBank': 'DrainMineBank',
    'DrainMineItemBank': 'DrainMineBank',
    'drainSurveyDataUnitsBank': 'DrainSDUBank',
    'DrainSurveyDataUnitsBank': 'DrainSDUBank',
    // Game State
    'activateGameState': 'ActivateGameState',
    'ActivateGameState': 'ActivateGameState',
    'copyGameState': 'CopyGameState',
    'CopyGameState': 'CopyGameState',
    // Crew
    'mintCrewToGame': 'MintCrew',
    'MintCrewToGame': 'MintCrew'
};

export default OP_MAP;
